if (CMAKE_SYSTEM_PROCESSOR MATCHES "^aarch64")
  string(APPEND CMAKE_C_FLAGS "-mcmodel=small")
  string(APPEND CMAKE_Fortran_FLAGS "-mcmodel=small")
else ()
  if (APPLE)
    string(APPEND CMAKE_C_FLAGS " -mcmodel=small")
    string(APPEND CMAKE_Fortran_FLAGS " -mcmodel=small")
  else()
    string(APPEND CMAKE_C_FLAGS " -mcmodel=large")
    string(APPEND CMAKE_Fortran_FLAGS " -mcmodel=large")
  endif()
endif()
string(APPEND CMAKE_Fortran_FLAGS " -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none")
if (CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER_EQUAL 10)
   string(APPEND CMAKE_Fortran_FLAGS " -fallow-argument-mismatch")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU")
if (compile_threaded)
  string(APPEND CMAKE_C_FLAGS " -fopenmp")
  string(APPEND CMAKE_CXX_FLAGS " -fopenmp")
  string(APPEND CMAKE_Fortran_FLAGS " -fopenmp")
  string(APPEND CMAKE_EXE_LINKER_FLAGS " -fopenmp")
endif()
string(APPEND CMAKE_C_FLAGS_DEBUG " -g -Wall -fbacktrace -fcheck=bounds -ffpe-trap=invalid,zero,overflow")
string(APPEND CMAKE_CXX_FLAGS_DEBUG " -g -Wall -fbacktrace")
string(APPEND CMAKE_Fortran_FLAGS_DEBUG " -g -Wall -fbacktrace -fcheck=bounds,pointer -ffpe-trap=invalid,zero,overflow")
string(APPEND CPPDEFS_DEBUG " -DYAKL_DEBUG")
string(APPEND CMAKE_C_FLAGS_RELEASE " -O")
string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O")
if (COMP_NAME STREQUAL csm_share)
  string(APPEND CMAKE_C_FLAGS " -std=c99")
endif()
string(APPEND CMAKE_Fortran_FORMAT_FIXED_FLAG " -ffixed-form")
string(APPEND CMAKE_Fortran_FORMAT_FREE_FLAG " -ffree-form")
string(APPEND CMAKE_C_FLAGS " -DNETCDF_ENABLE_LEGACY_MACROS")
set(ALQUIMIA_PATH $ENV{ALQUIMIA_PATH})
set(PFLOTRAN_PATH $ENV{PFLOTRAN_PATH}/src/pflotran)
set(PETSC_DIR $ENV{PETSC_DIR})
if (ALQUIMIA_PATH AND PFLOTRAN_PATH AND PETSC_DIR)
  if (COMP_NAME STREQUAL "elm")
    string(APPEND CPPDEFS " -DELM_USE_ALQUIMIA")
    string(APPEND CMAKE_C_FLAGS " -I${ALQUIMIA_PATH}/include -I${PETSC_DIR}/include")
    string(APPEND CMAKE_CXX_FLAGS " -I${ALQUIMIA_PATH}/include -I${PETSC_DIR}/include")
    string(APPEND CMAKE_Fortran_FLAGS " -I${ALQUIMIA_PATH}/include")
    string(APPEND CMAKE_Fortran_FLAGS " -I${PFLOTRAN_PATH} -I${PETSC_DIR}/include")
  endif()
  if (COMP_NAME STREQUAL "cpl")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${ALQUIMIA_PATH}/lib -L${ALQUIMIA_PATH}/lib -lalquimia")    
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${PFLOTRAN_PATH} -L${PFLOTRAN_PATH} -lpflotranchem")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${PETSC_DIR}/lib -L${PETSC_DIR}/lib -lpetsc")
  endif()
endif()
set(MPICC "mpicc")
set(MPICXX "mpicxx")
set(MPIFC "mpif90")
if (CMAKE_C_COMPILER_ID MATCHES "GNU")
  set(SCC "gcc")
  set(SCXX "g++")
else()
  set(SCC "clang")
  set(SCXX "clang++")
endif()
set(SFC "gfortran")
