set(CXX_LINKER "CXX")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,$ENV{FC_ROOT}/lib")
set(ALQUIMIA_PATH $ENV{ALQUIMIA_PATH})
set(PFLOTRAN_PATH $ENV{PFLOTRAN_PATH}/src/pflotran)
set(PETSC_DIR $ENV{PETSC_DIR})
if (ALQUIMIA_PATH AND PFLOTRAN_PATH AND PETSC_DIR)
  if (COMP_NAME STREQUAL "elm")
    string(APPEND CPPDEFS " -DUSE_ALQUIMIA_LIB")
    string(APPEND CMAKE_C_FLAGS " -I${ALQUIMIA_PATH}/include -I${PETSC_DIR}/include")
    string(APPEND CMAKE_CXX_FLAGS " -I${ALQUIMIA_PATH}/include -I${PETSC_DIR}/include")
    string(APPEND CMAKE_Fortran_FLAGS " -I${ALQUIMIA_PATH}/include")
    string(APPEND CMAKE_Fortran_FLAGS " -I${PFLOTRAN_PATH} -I${PETSC_DIR}/include")
  endif()
  if (COMP_NAME STREQUAL "cpl")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${ALQUIMIA_PATH}/lib -L${ALQUIMIA_PATH}/lib -lalquimia")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${PFLOTRAN_PATH} -L${PFLOTRAN_PATH} -lpflotranchem")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${PETSC_DIR}/lib -L${PETSC_DIR}/lib -lpetsc")
  endif()
endif()

