set(CXX_LINKER "CXX")
set(PIO_FILESYSTEM_HINTS "lustre")
string(APPEND FFLAGS " -O -fno-range-check")
string(APPEND FFLAGS " -fallow-argument-mismatch")
set(HDF5_PATH "$ENV{OLCF_HDF5_ROOT}")
set(NETCDF_PATH "$ENV{OLCF_NETCDF_C_ROOT}")
set(NETCDF_C_PATH "$ENV{OLCF_NETCDF_C_ROOT}")
set(NETCDF_FORTRAN_PATH "$ENV{OLCF_NETCDF_FORTRAN_ROOT}")
set(BLASLAPACK_LIBDIR "$ENV{OLCF_OPENBLAS_ROOT}/lib")
string(APPEND SLIBS " -Wl,-rpath=${NETCDF_C_PATH}/lib -L${NETCDF_C_PATH}/lib -lnetcdf")
string(APPEND SLIBS " -Wl,-rpath=${NETCDF_FORTRAN_PATH}/lib -L${NETCDF_C_PATH}/lib -lnetcdff")
string(APPEND SLIBS " -Wl,-rpath=${BLASLAPACK_LIBDIR} -L${BLASLAPACK_LIBDIR} -lopenblas")
string(APPEND CXX_LIBS " -lstdc++")
#set(ALQUIMIA_PATH "/nfs/data/ccsi/proj-shared/b0u/ELM-PFLOTRAN/alquimia/")
set(ALQUIMIA_PATH "/nfs/data/ccsi/proj-shared/E3SM/tools/alquimia-dev/v2021/")
set(PFLOTRAN_PATH "/nfs/data/ccsi/proj-shared/E3SM/tools/pflotran-elm-interface/v2021/")
string(APPEND FFLAGS " -I${ALQUIMIA_PATH}/include/alquimia")
string(APPEND SLIBS " -Wl,-rpath=${ALQUIMIA_PATH}/lib -L${ALQUIMIA_PATH}/lib -lalquimia -lpflotran_petsc_stubs")

