if (MPILIB STREQUAL openmpi)
  set(MPI_PATH "/usr")
endif()
set(HDF5_PATH "/home/f9y/Applications/hdf5-1.10.5-gcc")
set(NETCDF_PATH "/home/f9y/Applications/netcdf-4.x-hdf5-gcc")
set(CXX_LINKER "CXX")
string(APPEND FC_AUTO_R8 " -fdefault-real-8")
string(APPEND FFLAGS " -O -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none -fno-range-check")
string(APPEND FFLAGS_NOOPT " -O0")
string(APPEND FIXEDFLAGS " -ffixed-form")
string(APPEND FREEFLAGS " -ffree-form")
if (COMP_CLASS STREQUAL cpl)
  string(APPEND LDFLAGS " -L${NETCDF_PATH}/lib -Wl,-rpath=${NETCDF_PATH}/lib -lnetcdff -lnetcdf")
endif()
if (COMP_CLASS STREQUAL cpl)
  string(APPEND LDFLAGS " -L${HDF5_PATH}/lib -lhdf5_hl -lhdf5 -lhdf5hl_fortran -lhdf5_fortran")
endif()
if (COMP_CLASS STREQUAL cpl)
  string(APPEND LDFLAGS " -L/usr/lib -llapack -lblas")
endif()
set(MPICC "$ENV{MPI_PATH}/bin/mpicc")
set(MPICXX "$ENV{MPI_PATH}/bin/mpicxx")
set(MPIFC "$ENV{MPI_PATH}/bin/mpif90")
set(SCC "/usr/bin/gcc")
set(SCXX "/usr/bin/g++")
set(SFC "/usr/bin/gfortran")
set(SUPPORTS_CXX "TRUE")
