set(CXX_LINKER "CXX")
string(APPEND FC_AUTO_R8 " -fdefault-real-8")
string(APPEND FFLAGS " -O -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none -fno-range-check")
string(APPEND FIXEDFLAGS " -ffixed-form")
string(APPEND FREEFLAGS " -ffree-form")
set(HDF5_PATH "$ENV{HDF5_PATH}")
set(NETCDF_PATH "$ENV{NETCDF_PATH}")
set(NETCDF_C_PATH "$ENV{NETCDF_PATH}")
set(NETCDF_FORTRAN_PATH "$ENV{NETCDF_PATH}")
set(PNETCDF_PATH "$ENV{PNETCDF_PATH}")
set(LAPACK_LIBDIR "$ENV{BLASLAPACK_LIBDIR}")
if (NOT MPILIB STREQUAL mpi-serial)
  string(APPEND CFLAGS " -I/${NETCDF_C_PATH}/include -I/${HDF5_PATH}/include")
  string(APPEND FFLAGS " -I/${NETCDF_FORTRAN_PATH}/include -I/${NETCDF_C_PATH}/include -I/${HDF5_PATH}/include")
  string(APPEND SLIBS " -L${HDF5_PATH}/lib -Wl,-rpath=${HDF5_PATH}/lib -lhdf5_hl_fortran -lhdf5_fortran -lhdf5_hl -lhdf5")
  string(APPEND SLIBS " -L${NETCDF_C_PATH}/lib -Wl,-rpath=${NETCDF_C_PATH}/lib -lnetcdf")
  string(APPEND SLIBS " -L${NETCDF_FORTRAN_PATH}/lib -Wl,-rpath=${NETCDF_FORTRAN_PATH}/lib -lnetcdff")
endif()
if (MPILIB STREQUAL mpi-serial)
  string(APPEND SLIBS " -L$ENV{NETCDF_PATH}/lib -Wl,-rpath=$ENV{NETCDF_PATH}/lib -lnetcdff -lnetcdf")
endif()
string(APPEND CXX_LIBS " -lstdc++")
set(MPICC "mpicc")
set(MPICXX "mpic++")
set(MPIFC "mpif90")
set(SCC "gcc")
set(SCXX "g++")
set(SFC "gfortran")
set(SUPPORTS_CXX "TRUE")
set(ALQUIMIA_PATH "/nfs/data/ccsi/proj-shared/b0u/ELM-PFLOTRAN/alquimia_PE3/")