set(CXX_LINKER "CXX")
set(NETCDF_PATH "$ENV{NETCDF_PATH}")
set(NETCDF_C_PATH "$ENV{NETCDF_C_PATH}")
set(NETCDF_FORTRAN_PATH "$ENV{NETCDF_FORTRAN_PATH}")
set(PNETCDF_PATH "$ENV{PNETCDF_PATH}")
set(HDF5_PATH "$ENV{HDF5_PATH}")
set(LAPACK_LIBDIR "$ENV{BLASLAPACK_LIBDIR}")
string(APPEND CFLAGS " -I$ENV{NETCDF_PATH}/include -I$ENV{HDF5_PATH}/include")
string(APPEND FFLAGS " -I$ENV{NETCDF_PATH}/include -I$ENV{HDF5_PATH}/include")
string(APPEND LDFLAGS " -framework Accelerate")
if (COMP_CLASS STREQUAL cpl)
  string(APPEND LDFLAGS " -L${LAPACK_LIBDIR} -llapack -lblas")
endif()
if (compile_threaded)
  string(APPEND LDFLAGS " -L$ENV{CC_ROOT}/lib -lgomp")
endif()
string(APPEND SLIBS " -L$ENV{NETCDF_C_PATH}/lib -lnetcdf -L$ENV{HDF5_PATH}/lib")
string(APPEND SLIBS " -L$ENV{NETCDF_FORTRAN_PATH}/lib -lnetcdff -L$ENV{HDF5_PATH}/lib")
set(SFC "$ENV{FC_ROOT}/bin/gfortran")
set(SCC "$ENV{CC_ROOT}/bin/gcc")
set(SCXX "$ENV{CC_ROOT}/bin/g++")
set(MPICC "$ENV{MPI_ROOT}/bin/mpicc")
set(MPICXX "$ENV{MPI_ROOT}/bin/mpicxx")
set(MPIFC "$ENV{MPI_ROOT}/bin/mpifort")
