set(SUPPORTS_CXX "TRUE")
#set(PIO_FILESYSTEM_HINTS "nfs") # need a check
string(APPEND CMAKE_Fortran_FLAGS " -fallow-argument-mismatch")
set(HDF5_PATH $ENV{OLCF_HDF5_ROOT})
set(NETCDF_C_PATH $ENV{OLCF_NETCDF_C_ROOT})
set(NETCDF_FORTRAN_PATH $ENV{OLCF_NETCDF_FORTRAN_ROOT})
set(PNETCDF_PATH $ENV{OLCF_PARALLEL_NETCDF_ROOT})
set(BLASLAPACK_LIBDIR $ENV{OLCF_NETLIB_LAPACK_ROOT}/lib64)
string(APPEND SLIBS " -Wl,-rpath,${HDF5_PATH}/lib -L${HDF5_PATH}/lib -lhdf5_hl_fortran -lhdf5_fortran -lhdf5_hl -lhdf5")
string(APPEND SLIBS " -Wl,-rpath,${PNETCDF_PATH}/lib -L${PNETCDF_PATH}/lib -lpnetcdf")
string(APPEND SLIBS " -Wl,-rpath,${NETCDF_C_PATH}/lib -L${NETCDF_C_PATH}/lib -lnetcdf")
string(APPEND SLIBS " -Wl,-rpath,${NETCDF_FORTRAN_PATH}/lib -L${NETCDF_FORTRAN_PATH}/lib -lnetcdff")
string(APPEND SLIBS " -Wl,-rpath,${BLASLAPACK_LIBDIR} -L${BLASLAPACK_LIBDIR} -lblas -llapack")
string(APPEND CXX_LIBS " -lstdc++")
