set(SUPPORTS_CXX "TRUE")
#set(PIO_FILESYSTEM_HINTS "nfs") # need a check
#the following will override 'CMAKE_Fortran_FLAGS_DEBUG' from gnu.cmake, in which '-ffpt-trap=invalid' has seg. fault of 'mpi_init(ierr)' on pathfinder. A possible reason may be 'ierr' is 64-bit but should be 32-bit.
set(CMAKE_Fortran_FLAGS_DEBUG " -g -Wall -fbacktrace -fcheck=bounds,pointer -ffpe-trap=zero,overflow")
string(APPEND CMAKE_Fortran_FLAGS " -fallow-argument-mismatch")
#set(ALQUIMIA_PATH "/projects/hpcl-cli185/proj-shared/ccsi-apps/alquimia-pflotran/v2021/alquimia")
#set(PFLOTRAN_PATH "/projects/hpcl-cli185/proj-shared/ccsi-apps/alquimia-pflotran/v2021/pflotran")
set(ALQUIMIA_PATH $ENV{ALQUIMIA_PATH})
set(PFLOTRAN_PATH $ENV{PFLOTRAN_PATH})
set(PETSC_DIR $ENV{PETSC_DIR})
if (ALQUIMIA_PATH AND PFLOTRAN_PATH AND PETSC_DIR)
  if (COMP_NAME STREQUAL "elm")
    string(APPEND CPPDEFS " -DUSE_ALQUIMIA_LIB")
    string(APPEND CMAKE_C_FLAGS " -I${ALQUIMIA_PATH}/include")
    string(APPEND CMAKE_CXX_FLAGS " -I${ALQUIMIA_PATH}/include")
    string(APPEND CMAKE_Fortran_FLAGS " -I${ALQUIMIA_PATH}/include -I${PFLOTRAN_PATH} -I${PETSC_DIR}/include")
  endif()
  if (COMP_NAME STREQUAL "cpl")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${ALQUIMIA_PATH}/lib -L${ALQUIMIA_PATH}/lib -lalquimia")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${PFLOTRAN_PATH} -L${PFLOTRAN_PATH} -lpflotranchem")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${PETSC_DIR}/lib -L${PETSC_DIR}/lib -lpetsc")
  endif()
endif()
#sometimes cannot find libMoab.so on pathfinder
set(MOAB_ROOT /projects/hpcl-cli185/proj-shared/ccsi-apps/moab)
if (COMP_INTERFACE STREQUAL "moab")
  if (COMP_NAME STREQUAL "cpl")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${MOAB_ROOT}/lib -L${MOAB_ROOT}/lib")
  endif()
endif()
