if (MPILIB STREQUAL openmpi)
  set(MPI_PATH "$ENV{MPI_ROOT}")
endif()
set(HDF5_PATH "$ENV{HDF5_PATH}")
set(NETCDF_PATH "$ENV{NETCDF_PATH}")
set(LAPACK_LIBDIR "ENV{BLASLAPACK_DIR}")
if (COMP_CLASS STREQUAL cpl)
  string(APPEND LDFLAGS " -L$(NETCDF_PATH)/lib -lnetcdff -lnetcdf")
endif()
if (COMP_CLASS STREQUAL cpl)
  string(APPEND LDFLAGS " -L$(HDF5_PATH)/lib -lhdf5_hl -lhdf5 -lhdf5hl_fortran -lhdf5_fortran -lm -ldl -lz")
endif()
if (COMP_CLASS STREQUAL cpl)
  string(APPEND LDFLAGS " -L$(LAPACK_LIBDIR) -llapack -lblas")
endif()
set(SFC "$ENV{FC_ROOT}/bin/pgfortran")
set(SCC "$ENV{CC_ROOT}/bin/pgcc")
set(SCXX "$ENV{CC_ROOT}/bin/pgc++")
set(MPICC "$ENV{MPI_ROOT}/bin/mpicc")
set(MPICXX "$ENV{MPI_ROOT}/bin/mpicxx")
set(MPIFC "$ENV{MPI_ROOT}/bin/mpifort")
