message("PETSC_PATH: $ENV{PETSC_PATH}")
message("ELM_PFLOTRAN_SOURCE_DIR: $ENV{ELM_PFLOTRAN_SOURCE_DIR}")
if (NOT $ENV{PETSC_PATH} STREQUAL " " AND NOT $ENV{ELM_PFLOTRAN_SOURCE_DIR} STREQUAL " ")
  if (COMP_CLASS STREQUAL lnd)
    string(APPEND CPPDEFS " -DELM_PFLOTRAN -DCOLUMN_MODE")
    string(APPEND FFLAGS " -I${HDF5_PATH}/include")
    string(APPEND FFLAGS " -I$ENV{ELM_PFLOTRAN_SOURCE_DIR}")
    string(APPEND FFLAGS " -I$ENV{PETSC_PATH}/include")
  endif()
  if (COMP_CLASS STREQUAL cpl)
    string(APPEND LDFLAGS " -L${HDF5_PATH}/lib -Wl,-rpath,$ENV{HDF5_PATH}/lib -lhdf5_hl_fortran -lhdf5_fortran -lhdf5_hl -lhdf5 ")
    string(APPEND LDFLAGS " -L$ENV{ELM_PFLOTRAN_SOURCE_DIR} -lpflotran ")
    string(APPEND LDFLAGS " -L$ENV{PETSC_PATH}/lib -Wl,-rpath,$ENV{PETSC_PATH}/lib -lpetsc -lparmetis -lmetis ")
  endif()

endif()
