set(CXX_LINKER "CXX")
string(APPEND FC_AUTO_R8 " -fdefault-real-8")
string(APPEND CMAKE_Fortran_FLAGS " -O -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none -fno-range-check")
string(APPEND FIXEDFLAGS " -ffixed-form")
string(APPEND FREEFLAGS " -ffree-form")
set(HDF5_PATH "$ENV{HDF5_PATH}")
set(NETCDF_PATH "$ENV{NETCDF_PATH}")
set(PNETCDF_PATH "")
set(LAPACK_LIBDIR "$ENV{BLASLAPACK_LIBDIR}")
if (COMP_NAME STREQUAL "cpl")
  string(APPEND CMAKE_EXE_LINKER_FLAGS " -L${HDF5_PATH}/lib -Wl,-rpath=${HDF5_PATH}/lib -lhdf5_hl_fortran -lhdf5_fortran -lhdf5_hl -lhdf5")
  string(APPEND CMAKE_EXE_LINKER_FLAGS " -L${NETCDF_PATH}/lib -Wl,-rpath=${NETCDF_PATH}/lib -lnetcdff -lnetcdf")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -L${LAPACK_LIBDIR} -lblas -llapack")
endif()
set(MPICC "mpicc")
set(MPICXX "mpic++")
set(MPIFC "mpif90")
set(SCC "gcc")
set(SCXX "g++")
set(SFC "gfortran")
set(SUPPORTS_CXX "TRUE")
string(APPEND CMAKE_C_FLAGS " -DNETCDF_ENABLE_LEGACY_MACROS")
set(ALQUIMIA_PATH $ENV{ALQUIMIA_PATH})
set(PFLOTRAN_PATH $ENV{PFLOTRAN_PATH})
set(PETSC_DIR $ENV{PETSC_DIR})
if (ALQUIMIA_PATH AND PFLOTRAN_PATH AND PETSC_DIR)
  if (COMP_NAME STREQUAL "elm")
    string(APPEND CPPDEFS " -DUSE_ALQUIMIA_LIB")
    string(APPEND CMAKE_C_FLAGS " -I${ALQUIMIA_PATH}/include")
    string(APPEND CMAKE_CXX_FLAGS " -I${ALQUIMIA_PATH}/include")
    string(APPEND CMAKE_Fortran_FLAGS " -I${ALQUIMIA_PATH}/include -I${PFLOTRAN_PATH} -I${PETSC_DIR}/include")
  endif()
  if (COMP_NAME STREQUAL "cpl")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${ALQUIMIA_PATH}/lib -L${ALQUIMIA_PATH}/lib -lalquimia")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${PFLOTRAN_PATH} -L${PFLOTRAN_PATH} -lpflotranchem")
    string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-rpath,${PETSC_DIR}/lib -L${PETSC_DIR}/lib -lpetsc")
  endif()
endif()
